### ISSUE TITLE
Isolated Container

### ISSUE THREAD

**Issue by cml-paul** [Onemind-Services-LLC/cloudmydc-docs#127]
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/platform-overview/isolated-container

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163177555/40333a99-de10-40eb-be76-f66791b4efe1)

***No changes made yet, needs to remove Jelastic and Virtuozzo logos on animated gif.

**Comment by VKumar786** [comment]
@cml-paul sir, please can you generate a static image for same
