### ISSUE TITLE
Mount Points

### ISSUE THREAD

**Issue by dedithc** [Onemind-Services-LLC/cloudmydc-docs#135]
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/data-storage-container/data-sharing/mount-points

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163171081/d91b361e-91c2-4736-8762-b805750103d7)

***No changes made yet. Unable to remove Jelastic Domain Name.

**Comment by VKumar786** [comment]
@dedithc 
![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/142484106/d42f662e-786f-473a-90d7-0a787790e9d1)
