### ISSUE TITLE
Exporting Data For Sharing

### ISSUE THREAD

**Issue by dedithc** [Onemind-Services-LLC/cloudmydc-docs#136]
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/data-storage-container/data-sharing/exporting-data-for-sharing

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163171081/1ca1e20c-1d0f-4066-aba9-a7edd2445206)

***No changes made yet. Unable to remove Jelastic Domain Name.

**Comment by VKumar786** [comment]
@dedithc 
This needs to be retaken from the platform
