### ISSUE TITLE
Building Custom Container

### ISSUE THREAD

**Issue by cml-paul** [Onemind-Services-LLC/cloudmydc-docs#155]
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/container/building-custom-container

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163177555/eeeaa8bf-572c-40de-8aee-05ed364f3dc5)

Change image name

**Comment by VKumar786** [comment]
This should be `cloudmydc`
