### ISSUE TITLE
Java Options And Arguments

### ISSUE THREAD

**Issue by cml-paul** [Onemind-Services-LLC/cloudmydc-docs#160]
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/environment-management/environment-variables/java-options-and-arguments

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163177555/e30d6c3c-2aaa-4e95-9e42-4026a9049735)

Remove jelastic domain.

**Comment by VKumar786** [comment]
@cml-paul 
This needs to be retaken from the platform
