### ISSUE TITLE
Monitoring Consumed Resources

### ISSUE THREAD

**Issue by dedithc** [Onemind-Services-LLC/cloudmydc-docs#174]
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/account-and-pricing/resource-charging/monitoring-consumed-resources

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163171081/c7a89868-3182-4a5f-ba1f-7160bc76c024)

***No changes made yet. Need to remove Jelastic Domain Name.

**Comment by VKumar786** [comment]
@dedithc 
![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/142484106/7c8fa6e5-bb1f-43fc-86e6-9c4912964043)
