### ISSUE TITLE
Linux Vps Access Via Public Ip

### ISSUE THREAD

**Issue by dedithc** [Onemind-Services-LLC/cloudmydc-docs#181]
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/elastic-vps/elastic-vps-management/linux-vps-access-via-public-ip

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163171081/cd6a1141-d9dc-46e0-9f77-dd47982e4fac)

***No changes made yet. Unable to replicate. Needs to remove Jelastic Domain Name.

**Comment by VKumar786** [comment]
@dedithc 
![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/142484106/64ddce49-e2fc-49f7-9e65-dba70f08e8a6)
