### ISSUE TITLE
Nginx Balancer Configuration

### ISSUE THREAD

**Issue by dedithc** [Onemind-Services-LLC/cloudmydc-docs#186]
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/load-balancers/nginx/nginx-balancer-configuration

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163171081/5ef061a7-705c-47af-8d08-1828b8185700)

***No changes made yet. Needs to change Jelastic Domain Name.

**Comment by abhi1693** [comment]
This is not required
