### ISSUE TITLE
Add `Managing NetBox` subcategory

### ISSUE THREAD

**Issue by abhi1693** [Onemind-Services-LLC/cloudmydc-docs#40]
### Change Type

Addition

### Proposed Changes

Add `Managing NetBox` subcategory

- [x] NetBox Access
- [ ] Troubleshooting
- [ ] Upgrade

### Resolve By

2024-01-15

**Comment by abhi1693** [comment]
# NetBox Access

After the successful installation of your NetBox cluster on CloudMyDC, you can access the NetBox Web GUI to manage and document your network. Here's how to get started:

## Accessing NetBox Dashboard

1. Once installation is complete, a confirmation pop-up will provide the URL to your NetBox environment, along with the credentials needed for the first login. You'll also receive this information via an email notification.

![Screenshot from 2024-01-09 01-55-41](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/5083532/161cc477-fcf7-4763-8155-b2cddeb70f87)


2. To log in to the NetBox Dashboard, follow the provided URL. Click on the 'Login' button and enter your provided username and password.

![Screenshot from 2024-01-09 02-03-39](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/5083532/911ef6d3-22d9-4e5f-8674-d1c86b48b20a)

Remember, the username is typically the first part of your email address before the '@' symbol. Once logged in, you can start using NetBox to model and document your network infrastructure.

## Navigating the NetBox Dashboard

- The Dashboard provides an overview of your network's organization, devices, connections, and more, with a clean and user-friendly interface.
- Easily manage IP addresses, VLANs, racks, and other critical elements of your network infrastructure through the Web UI.

For further management tasks and customization, refer to the NetBox documentation or use the provided API for automation and integration with other systems.

**Comment by VKumar786** [comment]
> # Troubleshooting
> 
> If you encounter an error during the installation of NetBox, follow these steps to diagnose and resolve common issues.
> ## Step 1: Error Reporting
> 
> Upon installation failure, an error message will appear. You can report this by clicking the **Send Report** button to provide the error details to the support team.
> 
> ![download (1)](https://private-user-images.githubusercontent.com/5083532/296258250-6f2fe561-59c5-4d26-afdd-4ed0b90037ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDMyMTYsIm5iZiI6MTcwNTMwMjkxNiwicGF0aCI6Ii81MDgzNTMyLzI5NjI1ODI1MC02ZjJmZTU2MS01OWM1LTRkMjYtYWZkZC00ZWQwYjkwMDM3Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMDcxNTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA2ODQ5YTg0ZWIwNmM4ODI2NTcyNTNkMDJmMjlhZTVmYzUwMGFhOTc0OTllY2UyOTZkMzViMTA3MGQ2ZDViMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HZDewPndoZC1TO8aeYrqjx6deJmSPckpAVR4pc45eG0)
> ## Step 2: Reattempt Installation
> 
> Occasionally, issues can be fleeting and may be resolved by simply trying the installation process once more.
> ## Step 3: Check Container Logs
> 
> Logs provide valuable error messages and can be accessed via the dashboard:
> 
>     1. Select the NetBox environment.
> 
>     2. Click on the **Log** button for the relevant container.
> 
>     3. Look for error messages that indicate the problem.
> 
> 
> ## Step 4: Review NetBox Documentation
> 
> Consult the [NetBox Documentation](https://docs.netbox.dev/).
> ## Step 5: Consult Built-in Monitoring
> 
> Our built-in monitoring tools can offer insights and are detailed in the [documentation](/application-setting/built-in-monitoring/log-files).
> ## Step 6: Contact Support
> 
> If issues persist after the above steps, contact our support with:
> 
>     * A description of the problem.
> 
>     * Troubleshooting steps undertaken.
> 
>     * Relevant logs or error messages.
> 
> 
> Troubleshooting NetBox on CloudMyDC requires a systematic approach. If you're unable to resolve the issue, make use of available resources including community forums, NetBox issue tracker, and CloudMyDC's support.

Sir Documentation link is broken, please provide alternative to fix it

https://github.com/application-setting/built-in-monitoring/log-files

**Comment by abhi1693** [comment]
I didn't give you GitHub links. I gave real links from docs.cloudmydc.com. Check again, that's how you needed to add them in the md file
